import {
  Activity,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  AtSign,
  BarChart3,
  Bell,
  BookOpen,
  Bookmark,
  Brain,
  Cable,
  CalendarCheck,
  CalendarPlus,
  CalendarRange,
  Check,
  CheckCircle2,
  ChevronRight,
  CircleDot,
  Code2,
  Copy,
  Database,
  Download,
  Eye,
  EyeOff,
  Footprints,
  Gauge,
  GitCompare,
  Grip,
  Heart,
  HeartPulse,
  Hexagon,
  Info,
  Layers,
  LayoutDashboard,
  LibraryBig,
  Lightbulb,
  LineChart,
  Link,
  ListChecks,
  ListTree,
  LogOut,
  Map,
  MessageSquare,
  MessageSquareText,
  Minus,
  Moon,
  Mountain,
  MountainSnow,
  Palette,
  Pencil,
  PlugZap,
  Plus,
  Puzzle,
  Radio,
  RefreshCw,
  Repeat,
  Route,
  Ruler,
  Scale,
  Settings,
  Share2,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  Sparkles,
  Sun,
  Table2,
  Target,
  TentTree,
  TrendingDown,
  TrendingUp,
  TriangleAlert,
  Unlink,
  Unplug,
  User,
  Wand2,
  Watch,
  X,
} from 'lucide-react'
import type { CSSProperties } from 'react'
import type { LucideIcon } from 'lucide-react'

export interface IconProps {
  name: string
  size?: number
  color?: string
  style?: CSSProperties
  strokeWidth?: number
}

// Explicit registry (kebab-case → component) so only the icons we use are
// bundled. Add an entry here when introducing a new glyph name.
const REGISTRY: Record<string, LucideIcon> = {
  activity: Activity,
  'arrow-down-right': ArrowDownRight,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up': ArrowUp,
  'at-sign': AtSign,
  'bar-chart-3': BarChart3,
  bell: Bell,
  'book-open': BookOpen,
  bookmark: Bookmark,
  brain: Brain,
  cable: Cable,
  'calendar-check': CalendarCheck,
  'calendar-plus': CalendarPlus,
  'calendar-range': CalendarRange,
  check: Check,
  'check-circle-2': CheckCircle2,
  'chevron-right': ChevronRight,
  'circle-dot': CircleDot,
  'code-2': Code2,
  copy: Copy,
  database: Database,
  download: Download,
  eye: Eye,
  'eye-off': EyeOff,
  footprints: Footprints,
  gauge: Gauge,
  'git-compare': GitCompare,
  grip: Grip,
  heart: Heart,
  'heart-pulse': HeartPulse,
  hexagon: Hexagon,
  info: Info,
  layers: Layers,
  'layout-dashboard': LayoutDashboard,
  'library-big': LibraryBig,
  lightbulb: Lightbulb,
  'line-chart': LineChart,
  link: Link,
  'list-checks': ListChecks,
  'list-tree': ListTree,
  'log-out': LogOut,
  map: Map,
  'message-square': MessageSquare,
  'message-square-text': MessageSquareText,
  minus: Minus,
  moon: Moon,
  mountain: Mountain,
  'mountain-snow': MountainSnow,
  palette: Palette,
  pencil: Pencil,
  'plug-zap': PlugZap,
  plus: Plus,
  puzzle: Puzzle,
  radio: Radio,
  'refresh-cw': RefreshCw,
  repeat: Repeat,
  route: Route,
  ruler: Ruler,
  scale: Scale,
  settings: Settings,
  'share-2': Share2,
  shield: Shield,
  'shield-check': ShieldCheck,
  'sliders-horizontal': SlidersHorizontal,
  sparkles: Sparkles,
  sun: Sun,
  'table-2': Table2,
  target: Target,
  'tent-tree': TentTree,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  'triangle-alert': TriangleAlert,
  unlink: Unlink,
  unplug: Unplug,
  user: User,
  'wand-2': Wand2,
  watch: Watch,
  x: X,
}

/**
 * Icon — renders a Lucide glyph by its kebab-case name (matching the design
 * source). Falls back to an empty fixed-size box for unknown names.
 */
export function Icon({ name, size = 18, color, style, strokeWidth = 1.75 }: IconProps) {
  const Cmp = REGISTRY[name]
  if (!Cmp) {
    return <span style={{ display: 'inline-flex', width: size, height: size, flex: 'none', ...style }} />
  }
  return <Cmp size={size} color={color} strokeWidth={strokeWidth} style={{ flex: 'none', ...style }} />
}
